version: 2.1
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: 
         name: Install docker-compose and build images
         command: |
           docker build -t webbb .
  push:
    machine: true
    steps:
     - run:
         name: Installing gcloud sdk and push images gcr
         command: |
           sudo apt update
           sudo apt-get install apt-transport-https ca-certificates gnupg
           curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
           sudo apt-get update
           sudo apt-get install -y google-cloud-sdk
           echo "Installed"
           echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud_service_key.txt
           gcloud auth activate-service-account --key-file=${HOME}/gcloud_service_key.txt
           gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
           gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
           docker push eu.gcr.io ${GOOGLE_PROJECT_ID} webbb
workflows:
  version: 2.1
  build_and_push:
    jobs:
      - build:
         filters:
           branches:
             only: master
      - push:
         requires:
           - build